### ISSUE TITLE
REQUEST: Cebu Pacific A320Neo R E X  D A S H E R

### ISSUE THREAD

**Issue by PilotKetchum2002** [Lukeghrhgfhgh/Deleted-Multiliveries#1]
![texture-74](https://user-images.githubusercontent.com/107557660/204545558-25756cc0-187b-4c05-9ca5-0bc18e34e83b.jpg)

**Comment by GoldenFalcon54** [comment]
I'm gonna add that but please DO NOT use the issues page to submit liveries

**Comment by PilotKetchum2002** [comment]
> I'm gonna add that but please DO NOT use the issues page to submit liveries

Okay!
