### ISSUE TITLE
LIVERY REQUEST: Philippine Airlines B787-9 (Daniel Wresch's 24th Birthday Livery)

### ISSUE THREAD

**Issue by PilotKetchum2002** [Lukeghrhgfhgh/Deleted-Multiliveries#4]
![PAL789HappyBirthdayDanielWresch](https://user-images.githubusercontent.com/107557660/212499612-02d76f15-8e7d-4073-a606-509439b81a15.png)

**Comment by GoldenFalcon54** [comment]
We do add LiverySelector liveries just so you know

**Comment by PilotKetchum2002** [comment]
> We do add LiverySelector liveries just so you know

Yes! I'm Interested!
